name="App-morepub"
readme_from="script/morepub"
abstract_from="script/morepub"
authors_from="script/morepub"
license="gpl_3"
tag_format="v%v"

[ReleaseTest]
MinimumVersion = false

[release]
do_not_upload_to_cpan=true
