#!/bin/sh

set -e

[ -d fatlib ] || mkdir fatlib

rm -f morepub

fatpack trace --to-stderr script/morepub 2>&1 |  grep ^Mojo | while read pkg;do
	file="$(perldoc -l $pkg)"
	dir="fatlib/$(dirname $(echo $pkg | sed 's/::/\//g'))"
	mkdir -p "$dir"
	cp $file "$dir"
done
find fatlib -type f -print0 | xargs -0 perlstrip -s

fatpack file script/morepub > morepub

chmod +x morepub

rm -R fatlib
