=head1 NAME

morepub - minimal epub reader for the terminal

=head1 SYNOPSIS

  morepub EPUB_FILE

=head1 DESCRIPTION

morepub is a basic epub reader, that converts an epub to a single html
document. If stdin is connected to a tty the document is opened
with I<lynx(1)> otherwise the generated html is printed to stdout.

=head1 ENVIRONMENT

=over 4

=item MOREPUB_CMD

Command to call if morepub is not part of a pipeline. Defaults to 'lynx
-stdin'. Another nice command would be 'lynx -stdin -dump -nolist |
less'.

=back

=head1 COPYRIGHT AND LICENSE 

Copyright 2019 Mario Domgoergen C<< <mario@domgoergen.com> >> 

This program is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation, either version 3 of the License, or 
(at your option) any later version. 

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details. 

You should have received a copy of the GNU General Public License 
along with this program.  If not, see <http://www.gnu.org/licenses/>. 

