#!/bin/sh

set -e

minil release

./pack

last_tag=$(git describe --abbrev=0 --tags)

github-release release --user mdom --repo morepub --tag $last_tag
github-release upload  --user mdom --repo morepub --tag $last_tag --name morepub --file morepub
