#!/usr/bin/perl

use Mojo::Base -strict;
use FindBin '$Bin';
use lib "$Bin/../lib";
use App::morepub::Epub;

my $epub = shift;

my $book = App::morepub::Epub->new( file => $epub );

if ( -t STDOUT ) {
    open( my $fh, '|-', 'lynx', '-stdin')
      or die "Can't open less: $!\n";
    $book->render_book( $fh );
}
else {
    $book->render_book( \*STDOUT );
}

exit 0;

__END__

=head1 NAME

morepub - minimal epub reader for the terminal

=head1 SYNOPSIS

  morepub EPUB_FILE

=head1 DESCRIPTION

morepub is a basic epub reader, that converts an epub to a single html
document. If the controlly tty is a terminal the document is opened
with I<lynx(1)> otherwise the generated html is printed to stdout.

All internal links are rewritten and links to important sections of the
epub file are added to the top of the document.

=head1 COPYRIGHT AND LICENSE 

Copyright 2019 Mario Domgoergen C<< <mario@domgoergen.com> >> 

This program is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation, either version 3 of the License, or 
(at your option) any later version. 

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details. 

You should have received a copy of the GNU General Public License 
along with this program.  If not, see <http://www.gnu.org/licenses/>. 

=cut
